# .github/workflows/cron.yml
# https://crontab.guru/examples.html 

name: Cron test
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
     # end of everyday
    - cron:  '*/5 * * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: change dir
        run: |
          git config --global user.name 'peteryxu'
          cd /
          ls
          
          # etc
